# Generated by Django 5.1 on 2024-08-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('status', models.CharField(default='In_progress', max_length=100)),
            ],
        ),
    ]
